### ISSUE TITLE
 No implementation for org.eclipse.xtext.ui.refactoring.IReferenceUpdater was bound., ....ui.IRenameSupport$Factory was bound.

### ISSUE THREAD

**Issue by mikejramsey56** [rlogiacco/Natural#58]
I installed Natural but I am seeing these errors in my Eclipse error log.  My system is Windows 10.  Installed Software list is after the error message.

eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data file:/C:/Users/ramseym/mrisworkspace2/ -product org.eclipse.epp.package.java.product -clean

org.eclipse.ui
Error
Thu Aug 23 12:36:15 EDT 2018
The proxied handler for 'org.agileware.natural.cucumber.ui.CucumberExecutableExtensionFactory:org.eclipse.xtext.ui.refactoring.ui.IRenameElementHandler' could not be loaded

org.eclipse.core.runtime.CoreException: Guice configuration errors:

1) No implementation for org.eclipse.xtext.ui.refactoring.IReferenceUpdater was bound.
  while locating org.eclipse.xtext.ui.refactoring.IReferenceUpdater
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultLinkedPositionGroupCalculator.referenceUpdater(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ILinkedPositionGroupCalculator
    for field at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.linkedPositionGroupCalculator(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameElementHandler.renameRefactoringController(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameElementHandler

2) No implementation for org.eclipse.xtext.ui.refactoring.ui.IRenameSupport$Factory was bound.
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameSupport$Factory
    for field at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.renameSupportFactory(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameElementHandler.renameRefactoringController(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameElementHandler

2 errors (occurred in org.agileware.natural.cucumber.ui.CucumberExecutableExtensionFactory)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.handleCreationError(AbstractGuiceAwareExecutableExtensionFactory.java:96)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:64)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.handlers.HandlerProxy.loadHandler(HandlerProxy.java:350)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:231)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.setEnabled(E4HandlerProxy.java:127)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:80)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:862)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:179)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:220)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.showMenu(MenuManagerShowProcessor.java:255)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.menuAboutToHide(MenuManagerShowProcessor.java:112)
	at org.eclipse.jface.internal.MenuManagerEventHelper.showEventPostHelper(MenuManagerEventHelper.java:92)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:471)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:465)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:497)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:256)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5204)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4872)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1657)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:262)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:4279)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3811)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.eclipse.xtext.ui.refactoring.IReferenceUpdater was bound.
  while locating org.eclipse.xtext.ui.refactoring.IReferenceUpdater
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultLinkedPositionGroupCalculator.referenceUpdater(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ILinkedPositionGroupCalculator
    for field at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.linkedPositionGroupCalculator(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameElementHandler.renameRefactoringController(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameElementHandler

2) No implementation for org.eclipse.xtext.ui.refactoring.ui.IRenameSupport$Factory was bound.
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameSupport$Factory
    for field at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.renameSupportFactory(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController
    for field at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameElementHandler.renameRefactoringController(Unknown Source)
  while locating org.eclipse.xtext.ui.refactoring.ui.IRenameElementHandler

2 errors
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:57)
	... 59 more

Installed Software
  Buildship: Eclipse Plug-ins for Gradle	2.2.1.v20180125-1441	org.eclipse.buildship.feature.group	Eclipse Buildship
  Code Recommenders for Java Developers	2.5.2.v20180401-1226	org.eclipse.recommenders.rcp.feature.feature.group	Eclipse Code Recommenders
  Code Recommenders Mylyn Integration	2.5.2.v20180401-1226	org.eclipse.recommenders.mylyn.rcp.feature.feature.group	Eclipse Code Recommenders
  Code Recommenders News Feed	2.5.2.v20180401-1226	org.eclipse.recommenders.news.rcp.feature.feature.group	Eclipse Code Recommenders
  Code Recommenders Snipmatch	2.5.2.v20180401-1226	org.eclipse.recommenders.snipmatch.rcp.feature.feature.group	Eclipse Code Recommenders
  Cucumber Eclipse Feature	0.0.22.201806032001	cucumber.eclipse.feature.feature.group	null
  Cucumber Editor	0.7.6.201505100000	org.agileware.natural.cucumber.feature.feature.group	Roberto Lo Giacco
  EclEmma Java Code Coverage	3.1.0.201804041601	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.7.3.20180405-1200	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.13.4.v20180330-0919	org.eclipse.jdt.feature.group	Eclipse.org
  Eclipse Platform	4.7.3.v20180330-0640	org.eclipse.platform.feature.group	Eclipse.org
  Eclipse RCP	4.7.3.v20180330-0640	org.eclipse.rcp.feature.group	Eclipse.org
  Eclipse XML Editors and Tools	3.9.2.v201803221834	org.eclipse.wst.xml_ui.feature.feature.group	Eclipse Web Tools Platform
  Git integration for Eclipse	4.9.2.201712150930-r	org.eclipse.egit.feature.group	Eclipse EGit
  Git integration for Eclipse - Task focused interface	4.9.2.201712150930-r	org.eclipse.egit.mylyn.feature.group	Eclipse EGit
  Java implementation of Git	4.9.2.201712150930-r	org.eclipse.jgit.feature.group	Eclipse JGit
  m2e - Maven Integration for Eclipse (includes Incubating components)	1.8.3.20180227-2137	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  m2e - slf4j over logback logging (Optional)	1.8.3.20180227-2137	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Mylyn Builds Connector: Hudson/Jenkins	1.15.0.v20170411-2141	org.eclipse.mylyn.hudson.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Eclipse IDE	3.23.0.v20170411-2108	org.eclipse.mylyn.ide_feature.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Java Development	3.23.0.v20170411-2108	org.eclipse.mylyn.java_feature.feature.group	Eclipse Mylyn
  Mylyn Task List	3.23.1.v20170623-0008	org.eclipse.mylyn_feature.feature.group	Eclipse Mylyn
  Mylyn Task-Focused Interface	3.23.0.v20170414-0629	org.eclipse.mylyn.context_feature.feature.group	Eclipse Mylyn
  Mylyn Tasks Connector: Bugzilla	3.23.1.v20170623-0008	org.eclipse.mylyn.bugzilla_feature.feature.group	Eclipse Mylyn
  Mylyn Versions Connector: Git	1.15.0.v20170411-2003	org.eclipse.mylyn.git.feature.group	Eclipse Mylyn
  Mylyn WikiText	3.0.19.201711172000	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  Oomph Setup	1.9.0.v20180529-1103	org.eclipse.oomph.setup.feature.group	Eclipse Oomph Project
  Xtext Complete SDK	2.14.0.v20180523-0937	org.eclipse.xtext.sdk.feature.group	Eclipse Xtext

**Comment by rlogiacco** [comment]
Natural has not been updated to recent Eclipse versions due to lack of help or support on this project.
I'm left with two options: switch to a subscription model and get funds to bring the project on by myself or keep waiting for developers to join me.
Any alternative idea?
