### ISSUE TITLE
Editing .feature file causes "Error executing EValidator" in latest veresion of Eclipse

### ISSUE THREAD

**Issue by mikeauen** [rlogiacco/Natural#87]
When using the latest Natural plugin in the latest Eclipse to edit feature files, an error is immediately thrown in the file "Error executing EValidator". Not only is the error shown, but it also seems to prevent ctrl+click on the steps linking to the step files. Every developer on my team sees this same problem, but I cannot find anyone else complaining about this when doing google searches. Could this be a bug in the plugin, or is there a known way to address this in Eclipse?

**Comment by miklossy** [comment]
Based on the stacktrace from @mikeauen I could reproduce the problem with the following java program:

```
public class Main {

	public static void main(String[] args) {
		String pattern = "I navigate to {string} in the left hand menu";

		boolean result = "".matches(pattern);
		System.out.println(result);
	}

}
```

Executing this java program produces the same exception:

```
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 13
I navigate to {string} in the left hand menu
             ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.closure(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.matches(Unknown Source)
	at java.lang.String.matches(Unknown Source)
	at naturaltest.Main.main(Main.java:10)
```

The problem can be fixed by quoting the `regex` parameter of the `String.matches(String regex)` method call so that it represents a properly formatted reqular expression even if the text contains regex symbols like `{` and `}`.

@drkstr101 Could you please take a look and provide a PR with the corresponding fix?

![screencast](https://user-images.githubusercontent.com/20393472/91433255-4ed1cc80-e863-11ea-848e-4894a5c1f288.gif)

**Comment by drkstr101** [comment]
This is using cucumber-jvm5 compatible syntax. In theory it should not be that difficult to add support in [next](https://github.com/rlogiacco/Natural/pull/86). I had some WIP updates to the stepmatcher, but had backed them out to focus on the grammar lang for this release. In theory we just need to iterate the `Literal+` nodes in `RawText` and pluck out those which have a `grammerElement` of `STRING` or `NUMBER`, provided a non regex string in the step annotation.

**Comment by drkstr101** [comment]
This is [a lot more involved](https://github.com/rlogiacco/Natural/issues/89) than I originally thought. However, the upcoming release should treat these as a mismatched step, which would then be a configurable warning rather than a straight-up runtime exception thrown during validation.

**Comment by drkstr101** [comment]
@miklossy Thanks for the tip! I've [added some additional error protection](https://github.com/rlogiacco/Natural/blob/4b29b1c817e664eaefec0c4b13e243e98adb25ad/org.agileware.natural.stepmatcher.ui/src/org/agileware/natural/stepmatcher/ui/JavaAnnotationMatcher.java#L35) as you pointed out in your example. I should have tested against this new syntax once the stepmatcher was updated to target the new Gherkin annotation namespace. I've added an example to the stepmatcher test, and it is now at least flagging it as a mismatched step rather than a runtime exception. Perhaps we could add at least add some simple token matchers for things like `{string}` and `{number}`. Like something that can be done in a few lines of code.

**Comment by rlogiacco** [comment]
For having it working as expected in relation to step matching we will have
to:

1. Define a new non-terminal element
2. match curly braces and store the content
3. find if a method with the appropriate annotation and name exists in the
glue codebase

We can decide to skip the third step (I believe it's not going to be a very
fast operation) and avoid the storing part of the second step, but that
will imply either limited usability of the click-through feature or a true
pain in the ass.

**Comment by drkstr101** [comment]
What About something like this?

```java
public class CucumberExpressionValidator {

	private static final Pattern TOKEN_PATTERN = Pattern.compile("(?|({\\w+})|(\\(\\w+(\\s\\w+)?\\)))");

	public static boolean isMatchingAnnotationValue(final String annotationValue, final String description) {
		return matchRegex(annotationValue, description) || matchExpression(annotationValue, description);
	}

	private static boolean matchRegex(final String annotationValue, final String description) {
		try {
			return description.matches(Pattern.quote(annotationValue));
		} catch (final PatternSyntaxException e) {
			// PASS
		}

		return false;
	}

	private static boolean matchExpression(final String annotationValue, final String description) {
		int lastIndex = 0;
		final StringBuilder result = new StringBuilder();
		final Matcher matcher = TOKEN_PATTERN.matcher(annotationValue);
		while (matcher.find()) {
			result.append(annotationValue, lastIndex, matcher.start()).append(convertToken(matcher.group(1)));
			lastIndex = matcher.end();
		}

		if (lastIndex < annotationValue.length()) {
			result.append(annotationValue, lastIndex, annotationValue.length());
		}

		try {
			return description.matches(Pattern.quote(result.toString()));
		} catch (final PatternSyntaxException e) {
			e.printStackTrace();
		}

		return false;
	}

	private static String convertToken(final String token) {
		// TODO replace with equiv regex

		return token;
	}
}
```

This might be a little slow, however. I am not sure how best to branch between the two forms.

**Comment by rlogiacco** [comment]
I would keep this aside for now: let's focus on what we currently have. Once we get it working as expected we start adding features

**Comment by drkstr101** [comment]
Agreed.

**Comment by adityadubey057** [comment]
Hi Team,
Is there a fix for the same ?? I am facing the same issue as soon as I edited my Feature File on the First Line
**"Error Executing EValidator"**

**And this is the error I am getting on my Error Logs**

java.util.regex.PatternSyntaxException: Illegal repetition near index 24
Add APILoginPayLoad with {string} {string} {string} {string} {string}
                        ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.closure(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.matches(Unknown Source)
	at java.lang.String.matches(Unknown Source)
	at org.agileware.natural.common.JavaAnnotationMatcher.findMatches(JavaAnnotationMatcher.java:71)
	at org.agileware.natural.cucumber.validation.CucumberJavaValidator.checkStepMatching(CucumberJavaValidator.java:20)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:129)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:337)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:72)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:299)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:245)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:41)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:200)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:142)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:147)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:125)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)




![image](https://user-images.githubusercontent.com/84779344/126733048-80e84eb1-f81e-4dc6-900f-b96b868e4c70.png)
